apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: pythonapp
          image: 273354631576.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest
          ports:
            - containerPort: 5000
