apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-eks-app
  template:
    metadata:
      labels:
        app: flask-eks-app
    spec:
      containers:
        - name: flask-app
          image: <your-ecr-repo-uri>:latest
          ports:
            - containerPort: 5000
