apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
spec:
  type: LoadBalancer
  selector:
   name:python-app
    app: pythonapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
