name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]  # Only 3.8, since your self-hosted runner supports it

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests with retry logic
        run: |
          cd src
          retry=0
          until [ $retry -ge 3 ]
          do
            python -m pytest test_addition.py && break
            retry=$((retry+1))
            echo "Retrying test run... attempt #$retry"
            sleep 5
          done

          if [ $retry -ge 3 ]; then
            echo "❌ Tests failed after 3 attempts"
            exit 1
          fi


