name: My First GitHub Actions

on: [push]

#1. Push and Pull Request Trigger
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# 2. Scheduled Trigger (Cron Job)
# on:
#   schedule:
#     - cron: "0 0 * * 1"

# 3. Manual Trigger (Workflow Dispatch) 
# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Select environment'
#         required: true
#         default: 'staging'
#         type: choice
#         options:
#           - staging
#           - production


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
